### ISSUE TITLE
Style Transfer

### ISSUE THREAD

**Issue by HuaZheLei** [IDKiro/MCT#3]
Hi, I want to use this code to do style transfer as the paper says. How can I do it?

**Comment by IDKiro** [comment]
Sincerely, because the special training scheme, the MCT variants of AdaIN and WCT2 produce images that do not look so good and only surpass the baselines on some of the example images, which is the reason why quantitative comparisons on the style transfer task are not included in the paper.
We regret that we are unable to provide these unsatisfactory codes.
